<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Finanzplaner.ico</ApplicationIcon>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Finanzplaner.ico" />
    <None Remove="Assets\Finanzplaner_Startbild.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Finanzplaner.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Finanzplaner.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Finanzplaner_Startbild.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
